### ISSUE TITLE
Registry k8s can not correctly handle unregister when its scaled

### ISSUE THREAD

**Issue by denis-tingaikin** [networkservicemesh/sdk-k8s#456]
This problem has been reported on WG call.

## Scenario

Steps:
1.Deploy NSM
2. Scale registry-k8s to 4
3.Deploy NSE
4. Try to unregister NSE

**Actual**: NSE can not be unregistered
**Expected**: NSE can be unregistered

**Comment by NikitaSkrynnik** [comment]
@ljkiraly @zolug Hi, it looks like we won't be able to fix this bug in the current release. The problem is more complicated then we thought at the beginning and there is no a quick fix. Could you please tell why you want to scale registry so we can understand better how to rework it

**Comment by zolug** [comment]
Hi, we need to run multiple registry instances mostly to avoid API throttling which seemed to pop-up rather early when increasing the number of NSEs. And it also serves redundancy (e.g. in case of node failure).

**Comment by NikitaSkrynnik** [comment]
@zolug Hi, we can tune kubernetes go-client to handle more requests. Would it solve your problem if we tune parameters of the client or add some ENVs so you can tune them yourself?

About redundancy: `registry-k8s` is a deployment and if node fails it will be redeployed on another node. All data is stored in `etcd` so you won't lose it if node with registry fails. I'm not sure if it solves your problem. Could you please tell if you experienced any node failures with data loss?

**Comment by NikitaSkrynnik** [comment]
## Problem
There is one main problem with scaling registry - If we have several registries NSE can Register and Unregister in any of them.

## Options

### Option 1 - Master-Registry
Create a new component `master-registry` which acts as a load balancer. It calculates hash from NSE info on the first Register request and uses it to always send all requests from NSE to the same registry.

---

### Option 2 - Store connections on registry-clients
We can store connection to a registry on registry-clients and use it to always connect to the same registry on all requests.

**Comment by zolug** [comment]
Hi @NikitaSkrynnik,
In case of hashing the hash table (number of registries) might change, and so can the registry associated with a hash. This could be improved by linking the chosen registry to a connection, which is basically the second option. But what happens if the component storing the relation between connection and registry is lost for whatever reason? Let's consider if an Unregister is issued by the NSE before a Register could fill-in the missing info.

I think in general there's a problem in case the registry with the most recent resource ID is lost (e.g. due to scaling), and the NSE unregiters without sending a register.

I had an idea to distinguish between local timeout based Unregister() and Unregister() received from an other NSM component in k8s-registry, and only block the first. (There should be a single NSMgr handling an NSE, or the msgs would be directly coming from an NSE e.g., from a remote vlan nse.)
Not sure if it wold work, but it's prone to the same problem mentioned above (i.e. the registry with the most recent resource ID might not be around when the NSE wants to unregister). And forcing/crafting a Register before an Unregister sounds weird.

**Comment by NikitaSkrynnik** [comment]
@zolug Hi,
Thanks for the comment. I'm not sure about implementation details in the first option yet. The main idea is to use sharding for NSEs on `master-registry` to make them always go to the same registry.

About the second option:
I added a bit of details for this. If we lose the relation between connection and registry, NSE will choose another registry to do Unregister. We want to change `begin` element to allow NSE Unregister itself without Register event beforehand.

We are not sure about distiguishing between Unregister send from NSE and expire chain elements. We've discussed this option internally and decided to not use it because there is no simple way to do that.

**Comment by zolug** [comment]
> @zolug Hi, Thanks for the comment. I'm not sure about implementation details in the first option yet. The main idea is to use sharding for NSEs on `master-registry` to make them always go to the same registry.
> 
> About the second option: I added a bit of details for this. If we lose the relation between connection and registry, NSE will choose another registry to do Unregister. We want to change `begin` element to allow NSE Unregister itself without Register event beforehand.
> 
> We are not sure about distiguishing between Unregister send from NSE and expire chain elements. We've discussed this option internally and decided to not use it because there is no simple way to do that.

Do you also intend to get rid of the resource version check in the registry? Or how would a registry remove the custom resource if it had no or outdated version info? It might also require removal of the 'expire' element on the registry to avoid premature deletion in case of some event leading to registry re-select.

**Comment by NikitaSkrynnik** [comment]
@zolug Hello, 

> Do you also intend to get rid of the resource version check in the registry? Or how would a registry remove the custom resource if it had no or outdated version info?

No, we don't need to get rid of the resourse version checking. We've found a simple way to distiguish between Unregisters as you suggested above. We will let you know when we have an image for testing.

**Comment by denis-tingaikin** [comment]
Seems like done.

@zolug , @NikitaSkrynnik  Thanks!
